---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

env:
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=2.2

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install: []

install:
  # Install ansible
  - pip install ansible
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-lint tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
